//forward lookup zone
zone "IT23743380.lk" IN {
   type master;
   file "forward.IT23743380.lk";
   allow-update { none; };

};

//reverse look up zone

zone "33.74.23.in-addr.arpa" IN {
    type master;
    file "reverse.IT23743380.lk";
    allow-update { none; };
};



include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
